# Generated by Django 3.0.6 on 2020-06-17 10:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('sig_text', models.TextField()),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sigs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='SigParsed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('version', models.IntegerField(null=True)),
                ('sig_text', models.TextField()),
                ('method', models.CharField(max_length=100, null=True)),
                ('method_text_start', models.IntegerField(null=True)),
                ('method_text_end', models.IntegerField(null=True)),
                ('method_text', models.CharField(max_length=100, null=True)),
                ('dose', models.CharField(max_length=100, null=True)),
                ('dose_max', models.CharField(max_length=100, null=True)),
                ('dose_unit', models.CharField(max_length=100, null=True)),
                ('dose_text_start', models.IntegerField(null=True)),
                ('dose_text_end', models.IntegerField(null=True)),
                ('dose_text', models.CharField(max_length=100, null=True)),
                ('strength', models.CharField(max_length=100, null=True)),
                ('strength_max', models.CharField(max_length=100, null=True)),
                ('strength_unit', models.CharField(max_length=100, null=True)),
                ('strength_text_start', models.IntegerField(null=True)),
                ('strength_text_end', models.IntegerField(null=True)),
                ('strength_text', models.CharField(max_length=100, null=True)),
                ('route', models.CharField(max_length=100, null=True)),
                ('route_text_start', models.IntegerField(null=True)),
                ('route_text_end', models.IntegerField(null=True)),
                ('route_text', models.CharField(max_length=100, null=True)),
                ('frequency', models.IntegerField(null=True)),
                ('frequency_max', models.IntegerField(null=True)),
                ('period', models.IntegerField(null=True)),
                ('period_max', models.IntegerField(null=True)),
                ('period_unit', models.CharField(max_length=100, null=True)),
                ('time_duration', models.IntegerField(null=True)),
                ('time_duration_unit', models.CharField(max_length=100, null=True)),
                ('day_of_week', models.CharField(max_length=100, null=True)),
                ('time_of_day', models.CharField(max_length=100, null=True)),
                ('when', models.CharField(max_length=100, null=True)),
                ('offset', models.IntegerField(null=True)),
                ('bounds', models.IntegerField(null=True)),
                ('count', models.IntegerField(null=True)),
                ('frequency_text_start', models.IntegerField(null=True)),
                ('frequency_text_end', models.IntegerField(null=True)),
                ('frequency_text', models.CharField(max_length=100, null=True)),
                ('duration', models.IntegerField(null=True)),
                ('duration_max', models.IntegerField(null=True)),
                ('duration_unit', models.CharField(max_length=100, null=True)),
                ('duration_text_start', models.IntegerField(null=True)),
                ('duration_text_end', models.IntegerField(null=True)),
                ('duration_text', models.CharField(max_length=100, null=True)),
                ('as_needed', models.BooleanField(null=True)),
                ('indication', models.CharField(max_length=100, null=True)),
                ('indication_text_start', models.IntegerField(null=True)),
                ('indication_text_end', models.IntegerField(null=True)),
                ('indication_text', models.CharField(max_length=100, null=True)),
                ('sig', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sig_parsed', to='sig.Sig')),
            ],
            options={
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='SigReviewed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('sig_correct', models.BooleanField(null=True)),
                ('method_status', models.CharField(choices=[(0, 'incorrect'), (1, 'missing'), (2, 'optimize')], max_length=10, null=True)),
                ('dose_status', models.CharField(choices=[(0, 'incorrect'), (1, 'missing'), (2, 'optimize')], max_length=10, null=True)),
                ('strength_status', models.CharField(choices=[(0, 'incorrect'), (1, 'missing'), (2, 'optimize')], max_length=10, null=True)),
                ('route_status', models.CharField(choices=[(0, 'incorrect'), (1, 'missing'), (2, 'optimize')], max_length=10, null=True)),
                ('frequency_status', models.CharField(choices=[(0, 'incorrect'), (1, 'missing'), (2, 'optimize')], max_length=10, null=True)),
                ('duration_status', models.CharField(choices=[(0, 'incorrect'), (1, 'missing'), (2, 'optimize')], max_length=10, null=True)),
                ('indication_status', models.CharField(choices=[(0, 'incorrect'), (1, 'missing'), (2, 'optimize')], max_length=10, null=True)),
                ('themes', models.CharField(max_length=250, null=True)),
                ('notes', models.TextField(null=True)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sigs_reviewed', to=settings.AUTH_USER_MODEL)),
                ('sig_parsed', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sig_reviewed', to='sig.SigParsed')),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
