# Generated by Django 3.0.6 on 2020-06-17 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sig', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sigparsed',
            options={'ordering': ['-created']},
        ),
        migrations.AlterModelOptions(
            name='sigreviewed',
            options={'ordering': ['-created']},
        ),
        migrations.AddField(
            model_name='sigparsed',
            name='frequency_readable',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
