# Generated by Django 3.0.6 on 2020-06-26 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sig', '0002_auto_20200617_2142'),
    ]

    operations = [
        migrations.AddField(
            model_name='sigparsed',
            name='when_text',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sigparsed',
            name='when_text_end',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='sigparsed',
            name='when_text_start',
            field=models.IntegerField(null=True),
        ),
    ]
