# Generated by Django 3.0.6 on 2020-07-15 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sig', '0003_auto_20200626_1851'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sig',
            options={'ordering': ['-created']},
        ),
    ]
