# Generated by Django 3.2.9 on 2022-06-03 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sig', '0006_auto_20200724_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sigparsed',
            name='indication',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='sigparsed',
            name='indication_text',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
