# Generated by Django 3.2.9 on 2022-07-06 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sig', '0007_auto_20220603_2027'),
    ]

    operations = [
        migrations.AddField(
            model_name='sigparsed',
            name='dose_readable',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sigparsed',
            name='duration_readable',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sigparsed',
            name='indication_readable',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sigparsed',
            name='method_readable',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sigparsed',
            name='route_readable',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sigparsed',
            name='strength_readable',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sigparsed',
            name='when_readable',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
