# Generated by Django 3.2.9 on 2022-07-07 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sig', '0009_sig_sig_readable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sig',
            name='sig_readable',
        ),
        migrations.AddField(
            model_name='sigparsed',
            name='sig_readable',
            field=models.TextField(null=True),
        ),
    ]
