# Generated by Django 3.2.9 on 2022-07-18 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sig', '0010_auto_20220707_0254'),
    ]

    operations = [
        migrations.AddField(
            model_name='sigparsed',
            name='max_dose_denominator_unit',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sigparsed',
            name='max_dose_denominator_value',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sigparsed',
            name='max_dose_numerator_unit',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sigparsed',
            name='max_dose_numerator_value',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
