# Generated by Django 3.2.9 on 2022-07-18 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sig', '0011_auto_20220718_1626'),
    ]

    operations = [
        migrations.AddField(
            model_name='sigparsed',
            name='max_dose_readable',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sigparsed',
            name='max_dose_text',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sigparsed',
            name='max_dose_text_end',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='sigparsed',
            name='max_dose_text_start',
            field=models.IntegerField(null=True),
        ),
    ]
