# Generated by Django 3.2.9 on 2022-07-18 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sig', '0012_auto_20220718_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sigparsed',
            name='max_dose_denominator_value',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='sigparsed',
            name='max_dose_numerator_value',
            field=models.IntegerField(null=True),
        ),
    ]
