# Generated by Django 3.2.9 on 2022-07-18 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sig', '0013_auto_20220718_1816'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sigparsed',
            old_name='max_dose_denominator_unit',
            new_name='max_denominator_unit',
        ),
        migrations.RenameField(
            model_name='sigparsed',
            old_name='max_dose_denominator_value',
            new_name='max_denominator_value',
        ),
        migrations.RenameField(
            model_name='sigparsed',
            old_name='max_dose_numerator_unit',
            new_name='max_numerator_unit',
        ),
        migrations.RenameField(
            model_name='sigparsed',
            old_name='max_dose_numerator_value',
            new_name='max_numerator_value',
        ),
        migrations.RenameField(
            model_name='sigparsed',
            old_name='max_dose_readable',
            new_name='max_readable',
        ),
        migrations.RenameField(
            model_name='sigparsed',
            old_name='max_dose_text',
            new_name='max_text',
        ),
        migrations.RenameField(
            model_name='sigparsed',
            old_name='max_dose_text_end',
            new_name='max_text_end',
        ),
        migrations.RenameField(
            model_name='sigparsed',
            old_name='max_dose_text_start',
            new_name='max_text_start',
        ),
    ]
