# Generated by Django 3.2.9 on 2022-07-19 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sig', '0014_auto_20220718_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sigparsed',
            name='dose',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='sigparsed',
            name='dose_max',
            field=models.FloatField(null=True),
        ),
    ]
