# Generated by Django 3.2.9 on 2022-07-19 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sig', '0015_auto_20220719_1338'),
    ]

    operations = [
        migrations.AddField(
            model_name='sigparsed',
            name='max_dose_per_day',
            field=models.FloatField(null=True),
        ),
    ]
