# Generated by Django 3.2.9 on 2022-08-08 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sig', '0016_sigparsed_max_dose_per_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='sigparsed',
            name='additional_info',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='sigparsed',
            name='additional_info_readable',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='sigparsed',
            name='additional_info_text',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sigparsed',
            name='additional_info_text_end',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='sigparsed',
            name='additional_info_text_start',
            field=models.IntegerField(null=True),
        ),
    ]
