# Generated by Django 3.2.9 on 2022-08-12 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sig', '0017_auto_20220808_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sigparsed',
            name='route_text',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
