# Generated by Django 3.2.9 on 2022-08-12 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sig', '0018_alter_sigparsed_route_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sigparsed',
            name='indication_text',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
