# Generated by Django 3.2.9 on 2022-08-12 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sig', '0019_alter_sigparsed_indication_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sigparsed',
            name='additional_info_text',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='sigparsed',
            name='dose_text',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='sigparsed',
            name='duration_text',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='sigparsed',
            name='frequency_text',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='sigparsed',
            name='indication_text',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='sigparsed',
            name='max_text',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='sigparsed',
            name='method_text',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='sigparsed',
            name='strength_text',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='sigparsed',
            name='when_text',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
