# Generated by Django 3.2.9 on 2022-08-12 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sig', '0020_auto_20220812_0123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sigparsed',
            name='indication_text',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
