# Generated by Django 3.2.9 on 2022-12-14 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sig', '0021_alter_sigparsed_indication_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='sigreviewed',
            name='sig_corrected',
            field=models.TextField(null=True),
        ),
    ]
